-- =====================================================================
-- Malibou Chocolate — Migration 0006: Konversi products.id menjadi integer
-- -------------------------------------------------------------
-- Latar belakang:
--   - Skema awal (0.0.x) memakai `id text` (PRD001, ...).
--   - Skema baru di migrations/0001 mengubah id menjadi
--     `integer generated by default as identity`.
-- Migrasi ini mengonversi database yang SUDAH terisi dengan skema lama.
-- Untuk database baru (skema 0001 diterapkan langsung), migrasi ini
-- otomatis dilewati karena kolom id sudah bertipe integer.
--
-- Urutan kunci baru mengikuti sort_order lalu code agar konsisten
-- dengan buku besar katalog (migrations/0003).
-- =====================================================================

do $$
declare
    col_type text;
    max_id   integer;
begin
    select data_type
      into col_type
      from information_schema.columns
     where table_schema = 'public'
       and table_name   = 'products'
       and column_name  = 'id';

    if col_type = 'integer' then
        -- Database baru / sudah terkonversi: tidak ada yang perlu dilakukan.
        raise notice '[0006] products.id sudah integer, konversi dilewati.';
        return;
    end if;

    raise notice '[0006] Mengonversi products.id text -> integer.';

    -- 1) Cadangkan tabel lama beserta indeks & trigger-nya.
    alter table public.products rename to products_old;

    -- 2) Buat tabel baru dengan skema modern (integer identity).
    create table public.products (
        id          integer generated by default as identity primary key,
        code        text not null unique,
        name        text not null,
        category_id text not null references public.categories (id) on update cascade on delete restrict,
        price       integer not null check (price >= 0),
        unit        text not null default 'pcs',
        weight      text,
        description text not null default '',
        image_url   text not null,
        featured    boolean not null default false,
        sort_order  integer not null default 0,
        created_at  timestamptz not null default now(),
        updated_at  timestamptz not null default now()
    );

    comment on table public.products is 'Daftar produk katalog Malibou Chocolate.';

    -- 3) Salin data dengan id baru berurutan (sort_order, code).
    insert into public.products
        (id, code, name, category_id, price, unit, weight, description, image_url, featured, sort_order, created_at, updated_at)
    select
        row_number() over (order by sort_order, code) as id,
        code,
        name,
        category_id,
        price,
        coalesce(unit, 'pcs'),
        weight,
        description,
        image_url,
        coalesce(featured, false),
        sort_order,
        created_at,
        updated_at
    from public.products_old;

    -- 4) Lepas tabel lama (indeks & trigger ikut terhapus).
    drop table public.products_old;

    -- 5) Bangun ulang indeks pendukung.
    create index products_category_idx  on public.products (category_id);
    create index products_featured_idx  on public.products (featured);
    create index products_sort_order_idx on public.products (sort_order);

    -- 6) Trigger updated_at.
    create trigger products_set_updated_at
        before update on public.products
        for each row
        execute function public.set_updated_at();

    -- 7) RLS + kebijakan baca publik.
    alter table public.products enable row level security;

    drop policy if exists "products_public_read" on public.products;
    create policy "products_public_read"
        on public.products
        for select
        to anon, authenticated
        using (true);

    -- 8) Realtime publication (mungkin sudah berisi tabel lama —
    --    tambahkan lewat pemindahan trigger; aman karena tabel baru).
    begin
        alter publication supabase_realtime add table public.products;
        exception when duplicate_object then
            null;
    end;

    -- 9) Sinkronkan urutan identity dengan nilai maksimum.
    select coalesce(max(id), 1)
      into max_id
      from public.products;
    perform setval(pg_get_serial_sequence('public.products', 'id'), greatest(max_id, 1), true);

    raise notice '[0006] Konversi selesai: % produk memiliki id integer.', max_id;
end
$$;

-- =====================================================================
-- END Migrasi 0006
-- =====================================================================