-- =====================================================================
-- Malibou Chocolate — Migration 0008: Konversi categories.id menjadi integer
-- -------------------------------------------------------------
-- Latar belakang:
--   - Skema awal memakai `categories.id text` (slug: 'chocolate-bar', dll.)
--     sebagai primary key, dan products.category_id text menempel padanya.
--   - Untuk konsisten dengan products.id (integer), categories.id diubah
--     menjadi `integer generated by default as identity`.
-- Agar pemetaan aplikasi tetap stabil, ditambahkan kolom `slug` (nilai
-- slug lama dipertahankan) dan produk di-remap lewat slug tersebut.
--
-- Migrasi ini aman diulang: jika id sudah integer, langsung dilewati.
-- =====================================================================

do $$
declare
    col_type text;
    cat_count integer;
    prod_count integer;
begin
    select data_type
      into col_type
      from information_schema.columns
     where table_schema = 'public'
       and table_name   = 'categories'
       and column_name  = 'id';

    if col_type = 'integer' then
        -- Database baru / sudah dikonversi.
        raise notice '[0008] categories.id sudah integer, konversi dilewati.';
        return;
    end if;

    raise notice '[0008] Mengonversi categories.id text -> integer (+ slug).';

    -- 1) Cadangkan tabel kategori lama (slug sebagai PK).
    alter table public.categories rename to categories_old;

    -- 2) Tabel kategori baru: id integer identity + slug unik.
    create table public.categories (
        id          integer generated by default as identity primary key,
        slug        text not null unique,
        name        text not null,
        icon        text not null default '🍫',
        description text not null default '',
        sort_order  integer not null default 0,
        created_at  timestamptz not null default now()
    );

    comment on table public.categories is 'Kategori produk katalog Malibou Chocolate.';

    -- 3) Salin data; id berurutan mengikuti sort_order, slug = id lama.
    insert into public.categories
        (id, slug, name, icon, description, sort_order, created_at)
    select
        row_number() over (order by sort_order, id) as id,
        id as slug,
        name,
        coalesce(icon, '🍫'),
        coalesce(description, ''),
        sort_order,
        created_at
    from public.categories_old;

    -- 4) Cadangkan tabel produk lama (category_id text).
    alter table public.products rename to products_old;

    -- 5) Tabel produk baru: category_id integer references categories(id),
    --    tanpa kolom `code` (sudah dihapus di 0007).
    create table public.products (
        id          integer generated by default as identity primary key,
        name        text not null,
        category_id integer not null references public.categories (id) on update cascade on delete restrict,
        price       integer not null check (price >= 0),
        unit        text not null default 'pcs',
        weight      text,
        description text not null default '',
        image_url   text not null,
        featured    boolean not null default false,
        sort_order  integer not null default 0,
        created_at  timestamptz not null default now(),
        updated_at  timestamptz not null default now()
    );

    comment on table public.products is 'Daftar produk katalog Malibou Chocolate.';

    -- 6) Salin produk: id dipertahankan; category_id dipetakan lewat slug.
    insert into public.products
        (id, name, category_id, price, unit, weight, description, image_url, featured, sort_order, created_at, updated_at)
    select
        po.id,
        po.name,
        coalesce(cn.id, 1),
        po.price,
        po.unit,
        po.weight,
        po.description,
        po.image_url,
        po.featured,
        po.sort_order,
        po.created_at,
        po.updated_at
    from public.products_old po
    left join public.categories cn on cn.slug = po.category_id;

    -- 7) Lepas tabel lama.
    drop table public.products_old;
    drop table public.categories_old;

    -- 8) Indeks pendukung.
    create index products_category_idx     on public.products (category_id);
    create index products_featured_idx     on public.products (featured);
    create index products_sort_order_idx   on public.products (sort_order);
    create index categories_sort_order_idx on public.categories (sort_order);

    -- 9) Trigger updated_at.
    create trigger products_set_updated_at
        before update on public.products
        for each row
        execute function public.set_updated_at();

    -- 10) Row Level Security + kebijakan baca publik.
    alter table public.categories enable row level security;
    alter table public.products   enable row level security;

    drop policy if exists "categories_public_read" on public.categories;
    create policy "categories_public_read"
        on public.categories
        for select
        to anon, authenticated
        using (true);

    drop policy if exists "products_public_read" on public.products;
    create policy "products_public_read"
        on public.products
        for select
        to anon, authenticated
        using (true);

    -- 11) Realtime publication (bisa saja sudah berisi tabel dengan nama
    --     lama — tangani kasus sudah terdaftar).
    begin
        alter publication supabase_realtime add table public.categories;
        exception when duplicate_object then
            null;
    end;
    begin
        alter publication supabase_realtime add table public.products;
        exception when duplicate_object then
            null;
    end;

    -- 12) Sinkronkan urutan identity.
    select count(*) into cat_count from public.categories;
    perform setval(pg_get_serial_sequence('public.categories', 'id'), cat_count, true);
    select coalesce(max(id), 1) into prod_count from public.products;
    perform setval(pg_get_serial_sequence('public.products', 'id'), prod_count, true);

    raise notice '[0008] Konversi selesai: % kategori & % produk.', cat_count, prod_count;
end
$$;

-- =====================================================================
-- END Migrasi 0008
-- =====================================================================